Expense_Tracker/Models/ExpensesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Expense_Tracker.Models
{
    public class ExpensesViewModel
    {
        public int? Id { get; set; }

        [DataType(DataType.Date)]
        //[ValidExpenseDate(ErrorMessage ="invalid date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode =true)]
      
        [DateLessThanOrEqualToToday]
        public DateTime? ExpenseDate { get; set; }
        [RegularExpression(@"^\d+(?:\.\d+)?$", ErrorMessage = "Amount must be integer or decimal number.")]
        public string Amount { get; set; }
        public virtual int CategoryId { get; set; }    
        public string CategoryName { get; set; }
    }
}

Expense_Tracker/Controllers/ExpensesController.cs
using Expense_Tracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Expense_Tracker.Controllers
{
    public class ExpensesController : Controller
    {
        public readonly DatabaseContext _Db;
        public ExpensesController(DatabaseContext db)
        {
            _Db = db;
        }
        public IEnumerable<Expence> results { get; set; }
        [HttpPost]
        public IActionResult Index(DateTime? startDate, DateTime? endDate)
        {
            var results = (from a in _Db.Expenses
                           join b in _Db.Categories
                           on a.CategoryId equals b.CategoryId into ExpCat
                           from d in ExpCat.DefaultIfEmpty()

                           select new Expence
                           {
                               Id = a.Id,
                               ExpenseDate = a.ExpenseDate,
                               Amount = a.Amount,
                               CategoryName = d.CategoryName,
                               CategoryId = d.CategoryId
                           }).Where(x => x.ExpenseDate >= startDate && x.ExpenseDate <= endDate).ToList();
            //expList.OrderBy(a=> a.Id).Skip((currentPage - 1) * maxRows).Take()
            return View(results);
        }
        public IActionResult Index()
        {
            var expList = from a in _Db.Expenses
                          join b in _Db.Categories
                          on a.CategoryId equals b.CategoryId
                          into ExpCat
                          from d in ExpCat.DefaultIfEmpty()
                          
                          select new Expence 
                          {
                              Id = a.Id,
                              ExpenseDate = a.ExpenseDate,
                              Amount = a.Amount,
                              CategoryName = d.CategoryName,
                              CategoryId = d.CategoryId
                          };
            //expList.OrderBy(a=> a.Id).Skip((currentPage - 1) * maxRows).Take()
            return View(expList);

            
        }
       
        //public IActionResult Create(Expence expenceObj)
        //{
        //    CategoryDropdownlistLoad();
        //    return View(expenceObj);
        //}
        public async Task<IActionResult> Create(int id)
        {
            if (id == 0)
            {
                CategoryDropdownlistLoad();
                return View();
            }
            CategoryDropdownlistLoad();
            var ExpensesData = await _Db.Expenses.FindAsync(id);
            if (ExpensesData == null)
            {
                return NotFound();
            }
            ExpensesViewModel vmNew = new ExpensesViewModel();
            vmNew.Id = ExpensesData.Id;
            vmNew.CategoryId = ExpensesData.CategoryId;
            vmNew.CategoryName = ExpensesData.CategoryName;
            vmNew.ExpenseDate = ExpensesData.ExpenseDate;
            vmNew.Amount = ExpensesData.Amount;            
            return View(vmNew);            

        }

        [HttpPost]
        public async Task<IActionResult> AddExpense(ExpensesViewModel expenceObj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Expence newEx = new Expence();
                    if (expenceObj.Id == null)
                    {                        
                        newEx.ExpenseDate = (DateTime) expenceObj.ExpenseDate;
                        newEx.CategoryId = expenceObj.CategoryId;
                        newEx.Amount = expenceObj.Amount;
                    }
                    else
                    {
                        newEx.Id = (int) expenceObj.Id;
                        newEx.ExpenseDate = (DateTime) expenceObj.ExpenseDate;
                        newEx.CategoryId = expenceObj.CategoryId;
                        newEx.Amount = expenceObj.Amount;
                    }
                   
                    if (newEx.Id == 0)
                    {
                        _Db.Expenses.Add(newEx);
                        await _Db.SaveChangesAsync();
                    } else
                    {
                        _Db.Entry(newEx).State = EntityState.Modified;
                        await _Db.SaveChangesAsync();
                    }
                   
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Create");
              
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var ExpenseRecord = await _Db.Expenses.FindAsync(id);
                if (ExpenseRecord != null)
                {
                    _Db.Expenses.Remove(ExpenseRecord);
                    await _Db.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
               return RedirectToAction("Index");
                
            }
        }
        private void CategoryDropdownlistLoad()
        {
            try
            {
                List<ExpenceCategory> catList = new List<ExpenceCategory>();
                catList = _Db.Categories.ToList();
                catList.Insert(0, new ExpenceCategory { CategoryId = 0, CategoryName = "Please Select" });
                ViewBag.CategoryList = catList;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

Expense_Tracker/Views/Expenses/Create.cshtml
@model Expense_Tracker.Models.ExpensesViewModel

@{
    ViewData["Title"] = "Create";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddExpense">
            @Html.ValidationSummary(false);
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Expense Category</label>
                <select asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(ViewBag.CategoryList,"CategoryId","CategoryName"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseDate" class="control-label"></label>
                <input type="date"  asp-for="ExpenseDate" class="form-control" />
                <span asp-validation-for="ExpenseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.Id)
                <label asp-for="Amount" class="control-label"></label>
                <input type="text" asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Expense_Tracker/Views/Expenses/Index.cshtml
@model IEnumerable<Expense_Tracker.Models.Expence>

<h3 class="text-center text-info font-weight-bold">Expense Tracker</h3>
<p>
    <a class="float-right" asp-action="Create">Add New</a>
</p>
<p>
    @using (Html.BeginForm("Index", "Expenses", FormMethod.Post))
    {
        <label>From</label> <input type="date" name="startDate" />
        <label>To</label> <input type="date" name="endDate" />
        <input type="submit" value="Submit" class="btn btn-secondary" />
        <a asp-page="/Index">Get All</a>

        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Expense Category</th>
                    <th>Date of the Expense</th>
                    <th>Expense Amount.</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => item.CategoryName)</td>
                        @*<td hidden>@Html.DisplayFor(x => item.Id)</td>*@
                        <td>@Html.DisplayFor(x => item.ExpenseDate)</td>
                        <td>@Html.DisplayFor(x => item.Amount)</td>
                        @*<td>@Html.DisplayFor(x => item.CategoryId)</td>*@

                        <td>
                            @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>*@
                            @Html.ActionLink("Edit", "Create", new { item.Id }, new { @class = "btn btn-success" })|
                            @*<a asp-action="Details" asp-route-id="@item.CategoryId">Details</a> |*@
                            @*<a asp-action="Delete" asp-route-id="@item.CategoryId">Delete</a>*@
                            @Html.ActionLink("Delete", "Delete", new { item.Id }, new { @class = "btn btn-danger", onclick = "return confirm ('Do you really want to delete this record?')" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</p>